### PR TITLE
Addded custom curl options

### PR DESCRIPTION
**Pull request by natostanco**

### CODE REVIEW

**Comment by seregazhuk** [comment]
@natostanco thank you for your request. I've already implemented it in the latest version (4.6.0):

## Custom request settings

It is possible to override default Curl options for bot requests. For example you can 
set proxy and user-agent like this:

```php
$bot->getHttpClient->setOptions([
    CURLOPT_PROXY => 'xx.xx.xxx.xx:80',
    CURLOPT_USERAGENT => 'Your_User_Agent',
]);
```

**Comment by natostanco** [comment]
ok sorry then :p

**Comment by natostanco** [comment]
```
Fatal error: Uncaught exception 'seregazhuk\PinterestBot\Exceptions\WrongProviderException' with message 'Provider seregazhuk\PinterestBot\Api\Providers\Gethttpclient not found.' in /vol/usr/share/php/vendor/seregazhuk/pinterest-bot/src/Api/ProvidersContainer.php:79
```

**Comment by seregazhuk** [comment]
Oh, sorry. `getHttpClient` is a method, not a property. Try this:

```
$bot->getHttpClient()->setOptions([
    CURLOPT_PROXY => 'xx.xx.xxx.xx:80',
    CURLOPT_USERAGENT => 'Your_User_Agent',
]);
```

**Pull request closed without merging**
